language: emacs-lisp

matrix:
  fast_finish: true

script:
  - make
  - echo -e "travis_fold:start:make3\nline5\nline6\ntravis_fold:end:make3\n\nbetween\n\ntravis_fold:start:make4\nline7\nline8\ntravis_fold:end:make4\n"
  - echo "travis_fold:start:make5"
  - echo "line9"
  - echo "travis_fold:end:make5"
  - echo "end"
