language: emacs-lisp

matrix:
  fast_finish: true

script:
  - make
  - echo "travis_fold:start:make2"
  - echo "output2"
  - echo "travis_fold:end:make2"
  - echo "travis_fold:start:make3"
  - echo "output3"
  - echo "travis_fold:end:make3"
  - echo "end"
