language: emacs-lisp

matrix:
  fast_finish: true

script:
  - echo -e "travis_fold:start:make1\nline1\nline2\ntravis_fold:end:make1\n\nbetween\n\ntravis_fold:start:make4\nline3\nline4\ntravis_fold:end:make4\n"
  - echo "travis_fold:start:make2"
  - echo "output2"
  - echo "travis_fold:end:make2"
  - echo "travis_fold:start:make3"
  - echo "output3"
  - echo "travis_fold:end:make3"
  - echo "end"
